//! Proc macros for tower-mcp.
//!
//! Provides `#[tool]` as optional syntactic sugar over [`ToolBuilder`].
//! The macro generates builder code -- you can always eject to the builder
//! pattern for full control.
//!
//! Enable via the `macros` feature on `tower-mcp`:
//!
//! ```toml
//! tower-mcp = { version = "0.8", features = ["macros"] }
//! ```
//!
//! # Example
//!
//! ```rust,ignore
//! use tower_mcp::tool_fn;
//! use tower_mcp::CallToolResult;
//! use schemars::JsonSchema;
//! use serde::Deserialize;
//!
//! #[derive(Debug, Deserialize, JsonSchema)]
//! struct AddInput { a: i64, b: i64 }
//!
//! #[tool_fn(description = "Add two numbers")]
//! async fn add(input: AddInput) -> Result<CallToolResult, tower_mcp::Error> {
//!     Ok(CallToolResult::text(format!("{}", input.a + input.b)))
//! }
//!
//! // Generates a function `add_tool() -> tower_mcp::tool::Tool`
//! // that builds the tool using ToolBuilder internally.
//! ```

use proc_macro::TokenStream;
use quote::quote;
use syn::{ItemFn, LitStr, Token, parse_macro_input};

struct ToolAttrs {
    name: Option<String>,
    description: Option<String>,
}

impl syn::parse::Parse for ToolAttrs {
    fn parse(input: syn::parse::ParseStream) -> syn::Result<Self> {
        let mut name = None;
        let mut description = None;

        while !input.is_empty() {
            let ident: syn::Ident = input.parse()?;
            input.parse::<Token![=]>()?;
            let lit: LitStr = input.parse()?;

            if ident == "name" {
                name = Some(lit.value());
            } else if ident == "description" {
                description = Some(lit.value());
            } else {
                return Err(syn::Error::new_spanned(
                    ident,
                    "unsupported attribute (expected `name` or `description`)",
                ));
            }

            if !input.is_empty() {
                input.parse::<Token![,]>()?;
            }
        }

        Ok(ToolAttrs { name, description })
    }
}

/// Generates a tool constructor function from an async handler.
///
/// Applies to an `async fn` that takes a single typed input parameter
/// (implementing `Deserialize + JsonSchema`) and returns
/// `Result<CallToolResult, tower_mcp::Error>`.
///
/// # Attributes
///
/// - `description = "..."` -- tool description (required)
/// - `name = "..."` -- override the tool name (defaults to function name)
///
/// # Generated Code
///
/// For a function named `add`, generates `add_tool() -> tower_mcp::tool::Tool`.
///
/// The generated function calls `ToolBuilder` internally, so you can inspect
/// the expansion with `cargo expand`.
///
/// # Example
///
/// ```rust,ignore
/// #[tool_fn(description = "Add two numbers")]
/// async fn add(input: AddInput) -> Result<CallToolResult, tower_mcp::Error> {
///     Ok(CallToolResult::text(format!("{}", input.a + input.b)))
/// }
///
/// // Use it:
/// let router = McpRouter::new()
///     .server_info("my-server", "1.0.0")
///     .tool(add_tool());
/// ```
#[proc_macro_attribute]
pub fn tool_fn(args: TokenStream, input: TokenStream) -> TokenStream {
    let attrs = parse_macro_input!(args as ToolAttrs);
    let func = parse_macro_input!(input as ItemFn);

    let fn_name = &func.sig.ident;
    let tool_name_str = attrs
        .name
        .unwrap_or_else(|| fn_name.to_string().replace('_', "-"));

    let description = match attrs.description {
        Some(d) => quote! { .description(#d) },
        None => quote! {},
    };

    // Extract the input type from the function signature
    let inputs = &func.sig.inputs;
    if inputs.len() != 1 {
        return syn::Error::new_spanned(
            &func.sig,
            "tool_fn handler must have exactly one parameter (the input type)",
        )
        .to_compile_error()
        .into();
    }

    let input_arg = inputs.first().unwrap();
    let input_type = match input_arg {
        syn::FnArg::Typed(pat_type) => &pat_type.ty,
        syn::FnArg::Receiver(_) => {
            return syn::Error::new_spanned(input_arg, "tool_fn handler cannot take self")
                .to_compile_error()
                .into();
        }
    };

    // Generate the constructor function name: {fn_name}_tool
    let constructor_name = syn::Ident::new(&format!("{fn_name}_tool"), fn_name.span());

    let expanded = quote! {
        // Keep the original function
        #func

        /// Creates a [`Tool`](tower_mcp::tool::Tool) from the `#[tool_fn]`-annotated handler.
        ///
        /// Generated by `tower-mcp-macros`. Equivalent to:
        /// ```ignore
        /// ToolBuilder::new(#tool_name_str)
        ///     #description
        ///     .handler(|input| #fn_name(input))
        ///     .build()
        /// ```
        pub fn #constructor_name() -> tower_mcp::tool::Tool {
            tower_mcp::ToolBuilder::new(#tool_name_str)
                #description
                .handler(|input: #input_type| #fn_name(input))
                .build()
        }
    };

    expanded.into()
}
